CLOSE TABLE ALL
USE FACTURACION IN 1
SELE 1
COPY STRUC TO C:\WINDOWS\ESCRITORIO\FACTURACION
USE C:\WINDOWS\ESCRITORIO\FACTURACION IN 2
SELE 1
SET ORDER TO LOTE
SEEK "000002"
DO WHILE NOT EOF() AND LOTE="000002"
	SCATTER MEMVAR
	WAIT WINDOWS "PASANDO FACTURA : "+M.NUMFAC NOWAIT
	SELE 2
	APPEND BLANK
	GATHER MEMVAR	
	SKIP
ENDDO
WAIT WINDOWS CLEAR
CLOSE TABLE ALL
