Return
clear
set safe off
set talk on
Close Table All
use ANTICIPO.DBF                   excl
zap            
append from c:\conta-cuyo2\anticipo.dbf
use ASIEMODE.DBF  excl
zap
append from c:\conta-cuyo2\asiemode.dbf
zap               
use ASIG_CUENTAS.DBF                  excl
zap
append from c:\conta-cuyo2\ASIG_CUENTAS.DBF                                     
use AUX_BENI.DBF                      excl
zap
append from c:\conta-cuyo2\AUX_BENI.DBF                                         
use AUX_CAJA.DBF                      excl
zap
append from c:\conta-cuyo2\AUX_CAJA.DBF                                         
use AUX_CHEQUETER.DBF                 excl
zap
append from c:\conta-cuyo2\AUX_CHEQUETER.DBF                                    
use AUX_CUENTA.DBF                    excl
zap
append from c:\conta-cuyo2\AUX_CUENTA.DBF                                       
use AUX_DETACONT.DBF                  excl
zap
append from c:\conta-cuyo2\AUX_DETACONT.DBF                                     
use AUX_DEUDAELE.DBF                  excl
zap
append from c:\conta-cuyo2\AUX_DEUDAELE.DBF                                     
use AUX_ENTREGA_RETENCIONES.DBF       excl
zap
append from c:\conta-cuyo2\AUX_ENTREGA_RETENCIONES.DBF                                         
use AUX_FAC.DBF                       excl
zap
append from c:\conta-cuyo2\AUX_FAC.DBF                                          
use AUX_FACCOM.DBF                    excl
zap
append from c:\conta-cuyo2\AUX_FACCOM.DBF                                       
use AUX_FACCOMSELE.DBF                excl
zap
append from c:\conta-cuyo2\AUX_FACCOMSELE.DBF                                   
use AUX_FACTURACION.DBF               excl
zap
append from c:\conta-cuyo2\AUX_FACTURACION.DBF                                  
use AUX_FACTURACION2.DBF              excl
zap
append from c:\conta-cuyo2\AUX_FACTURACION2.DBF                                 
use AUX_FICHA.DBF                     excl
zap
append from c:\conta-cuyo2\AUX_FICHA.DBF                                        
use AUX_FICHAPROV.DBF                 excl
zap
append from c:\conta-cuyo2\AUX_FICHAPROV.DBF                                    
use AUX_IMPUESTO.DBF                  excl
zap
*append from c:\conta-cuyo2\AUX_IMPUESTO.DBF                                     
*use AUX_IVACOMPRA.DBF                 excl
*zap
append from c:\conta-cuyo2\AUX_IVACOMPRA.DBF                                    
use AUX_IVAFACCOM.DBF                 excl
zap
append from c:\conta-cuyo2\AUX_IVAFACCOM.DBF                                    
use AUX_MOVBAN.DBF                    excl
zap
append from c:\conta-cuyo2\AUX_MOVBAN.DBF                                       
use AUX_MOVBAN2.DBF                   excl
zap
append from c:\conta-cuyo2\AUX_MOVBAN2.DBF                                      
use AUX_MOVBANCO.DBF                  excl
zap
append from c:\conta-cuyo2\AUX_MOVBANCO.DBF                                     
use AUX_MOVTAR.DBF                    excl
zap
append from c:\conta-cuyo2\AUX_MOVTAR.DBF                                       
use AUX_PENDIENTES.DBF                excl
zap
append from c:\conta-cuyo2\AUX_PENDIENTES.DBF                                   
*use AUX_PENDIENTES2.DBF               excl
*zap
*append from c:\conta-cuyo2\AUX_PENDIENTES2.DBF                                  
use AUX_RETENCIONES.DBF               excl
zap
append from c:\conta-cuyo2\AUX_RETENCIONES.DBF                                  
use AUX_SUMSAL.DBF                    excl
zap
append from c:\conta-cuyo2\AUX_SUMSAL.DBF                                       
use AUX_TARJETA.DBF                   excl
zap
append from c:\conta-cuyo2\AUX_TARJETA.DBF                                      
use AUX_TERCEROS.DBF                  excl
zap
append from c:\conta-cuyo2\AUX_TERCEROS.DBF                                     
use AUX_TERCEROS2.DBF                 excl
zap
append from c:\conta-cuyo2\AUX_TERCEROS2.DBF                                    
use AUX_VENCI.DBF                     excl
zap
append from c:\conta-cuyo2\AUX_VENCI.DBF                                        
use BANCOS.DBF                        excl
zap
append from c:\conta-cuyo2\BANCOS.DBF                                           
use CAJA.DBF                          excl
zap
append from c:\conta-cuyo2\CAJA.DBF                                             
use CENTROCOSTO.DBF                   excl
zap
append from c:\conta-cuyo2\CENTROCOSTO.DBF                                      
use CHEQUERAS.DBF                     excl
zap
append from c:\conta-cuyo2\CHEQUERAS.DBF                                        
use CHEQUETER.DBF                     excl
zap
append from c:\conta-cuyo2\CHEQUETER.DBF                                        
use COBRADORES.DBF                    excl
zap
append from c:\conta-cuyo2\COBRADORES.DBF                                       
use COD_BANCOS.DBF                    excl
zap
append from c:\conta-cuyo2\COD_BANCOS.DBF                                       
use CONCILIACIONES.DBF                excl
zap
append from c:\conta-cuyo2\CONCILIACIONES.DBF                                   
use CONTRASEÑA.DBF                    excl
zap
append from c:\conta-cuyo2\CONTRASEÑA.DBF                                       
use CUENCONT.DBF                      excl
zap
append from c:\conta-cuyo2\CUENCONT.DBF                                         
use CUOTAS.DBF                        excl
zap
append from c:\conta-cuyo2\CUOTAS.DBF                                           
use DATOS.DBF                         excl
zap
append from c:\conta-cuyo2\DATOS.DBF                                            
use DEPOSITO.DBF                      excl
zap
append from c:\conta-cuyo2\DEPOSITO.DBF                                         
use DEPOSITO1.DBF                     excl
zap
append from c:\conta-cuyo2\DEPOSITO1.DBF                                        
use DEPOSITO2.DBF                     excl
zap
append from c:\conta-cuyo2\DEPOSITO2.DBF                                        
use DET_CONCILIACIONES.DBF            excl
zap
append from c:\conta-cuyo2\DET_CONCILIACIONES.DBF                               
use DETACONT.DBF                      excl
zap
append from c:\conta-cuyo2\DETACONT.DBF                                         
use DETFACAUX.DBF                     excl
zap
append from c:\conta-cuyo2\DETFACAUX.DBF                                        
use DEUDA_ELE.DBF                     excl
zap
append from c:\conta-cuyo2\DEUDA_ELE.DBF                                        
use DIAS.DBF                          excl
zap
append from c:\conta-cuyo2\DIAS.DBF                                             
use EGRESOS.DBF                       excl
zap
append from c:\conta-cuyo2\EGRESOS.DBF                                          
use ENCABEZADO.DBF                    excl
zap
append from c:\conta-cuyo2\ENCABEZADO.DBF                                       
use EXCEL_RETEN.DBF                   excl
zap
append from c:\conta-cuyo2\EXCEL_RETEN.DBF                                      
use FACCOM.DBF                        excl
zap
append from c:\conta-cuyo2\FACCOM.DBF                                           
use FACVEN.DBF                        excl
zap
append from c:\conta-cuyo2\FACVEN.DBF                                           
use FOXUSER.DBF                       excl
zap
append from c:\conta-cuyo2\FOXUSER.DBF                                          
use IMP_FACTURACION.DBF               excl
zap
append from c:\conta-cuyo2\IMP_FACTURACION.DBF                                  
use IMP_ORDEN.DBF                     excl
zap
append from c:\conta-cuyo2\IMP_ORDEN.DBF                                        
use INDICE_INFLA.DBF                  excl
zap
append from c:\conta-cuyo2\INDICE_INFLA.DBF                                     
use INGRESOS.DBF                      excl
zap
append from c:\conta-cuyo2\INGRESOS.DBF                                         
use IVA_FACCOM.DBF                    excl
zap
append from c:\conta-cuyo2\IVA_FACCOM.DBF                                       
use IVACOMPRAS.DBF                    excl
zap
append from c:\conta-cuyo2\IVACOMPRAS.DBF                                       
use LIQUIDACIONES.DBF                 excl
zap
append from c:\conta-cuyo2\LIQUIDACIONES.DBF                                    
*use LIS_CHEQUE.DBF                    excl
*zap
*append from c:\conta-cuyo2\LIS_CHEQUE.DBF                                       
use LIS_LIQUIDACIONES.DBF             excl
zap
append from c:\conta-cuyo2\LIS_LIQUIDACIONES.DBF                                
use LIS_MOV_PEN_REG.DBF               excl
zap
append from c:\conta-cuyo2\LIS_MOV_PEN_REG.DBF                                  
use LIST_VENCI.DBF                    excl
zap
append from c:\conta-cuyo2\LIST_VENCI.DBF                                       
use LISTADO_INGRESOS.DBF              excl
zap
append from c:\conta-cuyo2\LISTADO_INGRESOS.DBF                                 
use LISTADO_TRANSFERENCIAS.DBF        excl
zap
append from c:\conta-cuyo2\LISTADO_TRANSFERENCIAS.DBF                           
use MOV_PEN_REGISTRACION.DBF          excl
zap
append from c:\conta-cuyo2\MOV_PEN_REGISTRACION.DBF                             
use MOV_PEN_REGISTRADOS.DBF           excl
zap
*append from c:\conta-cuyo2\MOV_PEN_REGISTRADOS.DBF                              
use MOVICONT.DBF                      excl
zap
append from c:\conta-cuyo2\MOVICONT.DBF                                         
use MOVIMIENTOS_BANCO.DBF             excl
zap
append from c:\conta-cuyo2\MOVIMIENTOS_BANCO.DBF                                
use MOVIMIENTOS_BANCOS.DBF            excl
zap
append from c:\conta-cuyo2\MOVIMIENTOS_BANCOS.DBF                               
use MOVTAR.DBF                        excl
zap
append from c:\conta-cuyo2\MOVTAR.DBF                                           
use OPERADORES.DBF                    excl
zap
append from c:\conta-cuyo2\OPERADORES.DBF                                       
                    
use ORDEN.DBF                         excl
zap
append from c:\conta-cuyo2\ORDEN.DBF                                            
use PAGOS.DBF                         excl
zap
append from c:\conta-cuyo2\PAGOS.DBF                                            
use PAGOSPROV.DBF                     excl
zap
append from c:\conta-cuyo2\PAGOSPROV.DBF                                        
use PAGOTARJETA.DBF                   excl
zap
append from c:\conta-cuyo2\PAGOTARJETA.DBF                                      
use PERIODO_ACTUAL.DBF                excl
zap
append from c:\conta-cuyo2\PERIODO_ACTUAL.DBF                                   
use PERIODOS.DBF                      excl
zap
append from c:\conta-cuyo2\PERIODOS.DBF                                         
use PROVEEDORES.DBF                   excl
zap
append from c:\conta-cuyo2\PROVEEDORES.DBF                                      
use RAMAS.DBF                         excl
zap
append from c:\conta-cuyo2\RAMAS.DBF                                            
use RETENCIONES.DBF                   excl
zap
append from c:\conta-cuyo2\RETENCIONES.DBF                                      
use SALDO_PROV.DBF                    excl
zap
append from c:\conta-cuyo2\SALDO_PROV.DBF                                       
use SECTORES.DBF                      excl
zap
append from c:\conta-cuyo2\SECTORES.DBF                                         
use TABLA15.DBF                       excl
zap
append from c:\conta-cuyo2\TABLA15.DBF                                          
use TARJETAS.DBF                      excl
zap
append from c:\conta-cuyo2\TARJETAS.DBF                                         
use TIPO_ALICUOTAS.DBF                excl
zap
append from c:\conta-cuyo2\TIPO_ALICUOTAS.DBF                                   
use TIPO_ASIENTOS.DBF                 excl
zap
append from c:\conta-cuyo2\TIPO_ASIENTOS.DBF                                    
use TIPO_CAJA.DBF                     excl
zap
append from c:\conta-cuyo2\TIPO_CAJA.DBF                                        
use TIPO_DOCUMENTO.DBF                excl
zap
append from c:\conta-cuyo2\TIPO_DOCUMENTO.DBF                                   
use TIPO_LIQUIDACION.DBF              excl
zap
append from c:\conta-cuyo2\TIPO_LIQUIDACION.DBF                                 
use TIPO_ORDEN.DBF                    excl
zap
append from c:\conta-cuyo2\TIPO_ORDEN.DBF                                       
use TIPO_RETENCIONES.DBF              excl
zap
append from c:\conta-cuyo2\TIPO_RETENCIONES.DBF                                 
use TIPOCUENTA.DBF                    excl
zap
append from c:\conta-cuyo2\TIPOCUENTA.DBF                                       
use TIPOGASTO.DBF                     excl
zap
append from c:\conta-cuyo2\TIPOGASTO.DBF                                        
use TRANSFERENCIAS.DBF                excl
zap
append from c:\conta-cuyo2\TRANSFERENCIAS.DBF                                   
use VENCI_COMPRA.DBF                  excl
zap
append from c:\conta-cuyo2\VENCI_COMPRA.DBF                                     
use VENCI_COMPRAS.DBF                 excl
zap
append from c:\conta-cuyo2\VENCI_COMPRAS.DBF         
set safe on               
set talk off            